usingnamespace @import("env.zig");

pub const Colors = struct {
    w: []const u8,
    ww: []const u8,
    r: []const u8,
    rr: []const u8,
    g: []const u8,
    gg: []const u8,
    y: []const u8,
    yy: []const u8,
    b: []const u8,
    bb: []const u8,
    m: []const u8,
    mm: []const u8,
    c: []const u8,
    cc: []const u8,
    d: []const u8,
    dd: []const u8,
    x: []const u8,
    z: []const u8,
};

pub const ansi = Colors{
    .d = "\x1B[30m",
    .dd = "\x1B[90m",
    .r = "\x1B[31m",
    .rr = "\x1B[91m",
    .g = "\x1B[32m",
    .gg = "\x1B[92m",
    .y = "\x1B[33m",
    .yy = "\x1B[93m",
    .b = "\x1B[34m",
    .bb = "\x1B[94m",
    .m = "\x1B[35m",
    .mm = "\x1B[95m",
    .c = "\x1B[36m",
    .cc = "\x1B[96m",
    .w = "\x1B[37m",
    .ww = "\x1B[97m",
    .x = "\x1B[0m",
    .z = "\x1B[1m",
};

pub const mono = Colors{
    .d = "",
    .dd = "",
    .r = "",
    .rr = "",
    .g = "",
    .gg = "",
    .y = "",
    .yy = "",
    .b = "",
    .bb = "",
    .m = "",
    .mm = "",
    .c = "",
    .cc = "",
    .w = "",
    .ww = "",
    .x = "",
    .z = "",
};

pub const Logo = struct {
    motif: []const u8,
    logo: [8][]const u8,
};

pub const OsEnum = enum {
    alpine,
    android,
    astra,
    archbang,
    arco,
    arch,
    archlabs,
    artix,
    centos,
    debian,
    elementary,
    endeavour,
    fedora,
    garuda,
    gentoo,
    kubuntu,
    manjaro,
    mint,
    msys2,
    mx,
    nixos,
    opensuse,
    parabola,
    postmarket,
    qubes,
    raspbian,
    redhat,
    slackware,
    ubuntu,
    void,
    zorin,
    generic,
};

pub const Args = struct {
    colors: bool,
    help: bool,
    logo: ?OsEnum,
};
